[project]
name = "app-name"
version = "0.1.0"
description = "Your description here"
authors = [
    { name = "Oluwasemire Ajayi" }
    { name = "Kamsiyochi Ekenulo" }
    { name = "Joseph Nnabueze" }
    { name = "Chimdike Agugoesi" }
    { name = "Chianugo Onyia " }
    { name = "Osinachi Justin-Sonde" }
    { name = "Marvelous Moses-Okorie" }
]
readme = "README.md"
requires-python = ">=3.10"

dependencies = []

[project.scripts]
ruin-game = "the_ruin_and_the_green.main:main"